import { ArrowRightCircleIcon } from '@heroicons/react/20/solid';

export const core = [
  {
    id: 1,
    content: 'Introduction to Remote Software Development',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 2,
    content: 'Pair programming and collaboration',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 3,
    content: 'Essential Technical Skills',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 4,
    content: 'Essential Soft Skills',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 5,
    content: 'AI Collaboration and Personalization',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 6,
    content: 'Interactive Project-Based Learning',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 7,
    content: 'Open-Source Software Contributions',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 8,
    content: 'Community Contributions and Milestones',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 9,
    content: 'Remote Work Preparedness',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 10,
    content: 'Portfolio Development and Certification',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
];

export const project = [
  {
    id: 1,
    content: 'Project setup and version control',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'project_setup_and_version_control',
  },
  {
    id: 2,
    content: 'Write a project overview',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'write_a_project_overview',
  },
  {
    id: 3,
    content: 'Design user interface mockups',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'design_user_interface_mockups',
  },
  {
    id: 4,
    content: 'Pitch the project idea',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'pitch_the_project_idea',
  },
  {
    id: 5,
    content: 'Develop basic frontend functionality',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'develop_basic_frontend_functionality',
  },
  {
    id: 6,
    content: 'Blog post on project progress',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'blog_post_on_project_progress',
  },
  {
    id: 7,
    content: 'Backend development (user management)',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'backend_development_user_management',
  },
  {
    id: 8,
    content: 'Remote team collaboration simulation',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'remote_team_collaboration_simulation',
  },
  {
    id: 9,
    content: 'Implement chat and file-sharing features',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'implement_chat_and_file_sharing_features',
  },
  {
    id: 10,
    content: 'Conduct a user feedback session',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'conduct_a_user_feedback_session',
  },
  {
    id: 11,
    content: 'Integrate third-party APIs',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'integrate_third_party_apis',
  },
  {
    id: 12,
    content: 'Create a project demo video',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'create_a_project_demo_video',
  },
  {
    id: 13,
    content: 'Perform code review and optimization',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'perform_code_review_and_optimization',
  },
  {
    id: 14,
    content: 'Social media promotion',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
    slug: 'social_media_promotion',
  },
];

export const oss = [
  {
    id: 1,
    content: 'Research open-source projects',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 2,
    content: "Join the project's community",
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 3,
    content: 'Explore the codebase',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 4,
    content: 'Identify an issue or feature request',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 5,
    content: 'Propose a solution',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 6,
    content: 'Implement the solution',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 7,
    content: 'Test your solution',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 8,
    content: 'Submit a pull request',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 9,
    content: 'Participate in code review',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 10,
    content: 'Mentor a newcomer',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 11,
    content: 'Document your experience',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 12,
    content: 'Share your work',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 13,
    content: 'Contribute to project documentation',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
  {
    id: 14,
    content: 'Reflect on your open-source journey',
    icon: ArrowRightCircleIcon,
    iconBackground: 'bg-purple-500',
  },
];
